package Ch15;

// 예외를 생성 : throw
// 예외를 던짐 : throws

class A{
	
	public void Ex1() throws NullPointerException {
		

		System.out.println("Ex1 process..1");
		throw new NullPointerException("Ex1 Null Exception");	// 예외 직접 생성

		System.out.println("Ex1 process..2");	// 예외 발생으로 오류 생김 -> 1. 상단 예외 직접 관리하는 try-catch방식
	}
	
}
class B{
	
}

public class C05ThrowAndThrowsMain {
	public static void main(String[] args) {
		
		System.out.println("실행코드1");
		System.out.println("실행코드2");
		A a = new A();
		B b = new B();
		
		a.Ex1();
		
		System.out.println("실행코드3");
		

	}
}
